version: '3.8'

services:
  roupas:

   build:
     context: .
   command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000
   volumes:
    - static_volume:/home/app/produtos/static
   expose:
    - 8000
  nginx:
   build: ./compose/nginx
   volumes:
    - static_volume:/home/app/produtos/static
   ports:
    - 80:80
   depends_on:
    - roupas
volumes:
  static_volume:
